//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:/Users/jonat/source/repos/QCoreV0/Software/QCoreV0/Quassel/ANTLR/qcal.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IqcalListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class qcalBaseListener : IqcalListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="qcalParser.code"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCode([NotNull] qcalParser.CodeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="qcalParser.code"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCode([NotNull] qcalParser.CodeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="qcalParser.code_line"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCode_line([NotNull] qcalParser.Code_lineContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="qcalParser.code_line"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCode_line([NotNull] qcalParser.Code_lineContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="qcalParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] qcalParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="qcalParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] qcalParser.StatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="qcalParser.instruction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInstruction([NotNull] qcalParser.InstructionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="qcalParser.instruction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInstruction([NotNull] qcalParser.InstructionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="qcalParser.directive"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDirective([NotNull] qcalParser.DirectiveContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="qcalParser.directive"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDirective([NotNull] qcalParser.DirectiveContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="qcalParser.container_start"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterContainer_start([NotNull] qcalParser.Container_startContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="qcalParser.container_start"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitContainer_start([NotNull] qcalParser.Container_startContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="qcalParser.container_end"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterContainer_end([NotNull] qcalParser.Container_endContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="qcalParser.container_end"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitContainer_end([NotNull] qcalParser.Container_endContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="qcalParser.parameter_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParameter_list([NotNull] qcalParser.Parameter_listContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="qcalParser.parameter_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParameter_list([NotNull] qcalParser.Parameter_listContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="qcalParser.parameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParameter([NotNull] qcalParser.ParameterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="qcalParser.parameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParameter([NotNull] qcalParser.ParameterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="qcalParser.parameter_identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParameter_identifier([NotNull] qcalParser.Parameter_identifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="qcalParser.parameter_identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParameter_identifier([NotNull] qcalParser.Parameter_identifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="qcalParser.parameter_value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParameter_value([NotNull] qcalParser.Parameter_valueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="qcalParser.parameter_value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParameter_value([NotNull] qcalParser.Parameter_valueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="qcalParser.regref"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRegref([NotNull] qcalParser.RegrefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="qcalParser.regref"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRegref([NotNull] qcalParser.RegrefContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
