//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:/Users/jonat/source/repos/QCoreV0/Software/QCoreV0/Quassel/ANTLR/qcal.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="qcalParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IqcalVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="qcalParser.code"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCode([NotNull] qcalParser.CodeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="qcalParser.code_line"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCode_line([NotNull] qcalParser.Code_lineContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="qcalParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] qcalParser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="qcalParser.instruction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInstruction([NotNull] qcalParser.InstructionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="qcalParser.directive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDirective([NotNull] qcalParser.DirectiveContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="qcalParser.container_start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitContainer_start([NotNull] qcalParser.Container_startContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="qcalParser.container_end"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitContainer_end([NotNull] qcalParser.Container_endContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="qcalParser.parameter_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameter_list([NotNull] qcalParser.Parameter_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="qcalParser.parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameter([NotNull] qcalParser.ParameterContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="qcalParser.parameter_identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameter_identifier([NotNull] qcalParser.Parameter_identifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="qcalParser.parameter_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameter_value([NotNull] qcalParser.Parameter_valueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="qcalParser.regref"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRegref([NotNull] qcalParser.RegrefContext context);
}
