//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:/Users/jonat/source/repos/QCoreV0/Software/QCoreV0/Quassel/ANTLR/qcal.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="qcalParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IqcalListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="qcalParser.code"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCode([NotNull] qcalParser.CodeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="qcalParser.code"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCode([NotNull] qcalParser.CodeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="qcalParser.code_line"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCode_line([NotNull] qcalParser.Code_lineContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="qcalParser.code_line"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCode_line([NotNull] qcalParser.Code_lineContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="qcalParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] qcalParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="qcalParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] qcalParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="qcalParser.instruction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInstruction([NotNull] qcalParser.InstructionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="qcalParser.instruction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInstruction([NotNull] qcalParser.InstructionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="qcalParser.directive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDirective([NotNull] qcalParser.DirectiveContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="qcalParser.directive"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDirective([NotNull] qcalParser.DirectiveContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="qcalParser.container_start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterContainer_start([NotNull] qcalParser.Container_startContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="qcalParser.container_start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitContainer_start([NotNull] qcalParser.Container_startContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="qcalParser.container_end"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterContainer_end([NotNull] qcalParser.Container_endContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="qcalParser.container_end"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitContainer_end([NotNull] qcalParser.Container_endContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="qcalParser.parameter_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameter_list([NotNull] qcalParser.Parameter_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="qcalParser.parameter_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameter_list([NotNull] qcalParser.Parameter_listContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="qcalParser.parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameter([NotNull] qcalParser.ParameterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="qcalParser.parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameter([NotNull] qcalParser.ParameterContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="qcalParser.parameter_identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameter_identifier([NotNull] qcalParser.Parameter_identifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="qcalParser.parameter_identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameter_identifier([NotNull] qcalParser.Parameter_identifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="qcalParser.parameter_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameter_value([NotNull] qcalParser.Parameter_valueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="qcalParser.parameter_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameter_value([NotNull] qcalParser.Parameter_valueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="qcalParser.regref"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRegref([NotNull] qcalParser.RegrefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="qcalParser.regref"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRegref([NotNull] qcalParser.RegrefContext context);
}
