//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:/Users/jonat/source/repos/QCoreV0/ANTLR Experiment/Quassel/qcal.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="qcalParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IqcalListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="qcalParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgram([NotNull] qcalParser.ProgramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="qcalParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgram([NotNull] qcalParser.ProgramContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="qcalParser.statement_block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement_block([NotNull] qcalParser.Statement_blockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="qcalParser.statement_block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement_block([NotNull] qcalParser.Statement_blockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="qcalParser.statement_seperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement_seperator([NotNull] qcalParser.Statement_seperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="qcalParser.statement_seperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement_seperator([NotNull] qcalParser.Statement_seperatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="qcalParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] qcalParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="qcalParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] qcalParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="qcalParser.parameter_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameter_list([NotNull] qcalParser.Parameter_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="qcalParser.parameter_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameter_list([NotNull] qcalParser.Parameter_listContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="qcalParser.parameter_separator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameter_separator([NotNull] qcalParser.Parameter_separatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="qcalParser.parameter_separator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameter_separator([NotNull] qcalParser.Parameter_separatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="qcalParser.parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameter([NotNull] qcalParser.ParameterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="qcalParser.parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameter([NotNull] qcalParser.ParameterContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="qcalParser.regref"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRegref([NotNull] qcalParser.RegrefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="qcalParser.regref"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRegref([NotNull] qcalParser.RegrefContext context);
}
